version: 2.1

executors:
  alpine:
    docker:
      - image: alpine:3.9
    working_directory: ~/
    environment:
      VERSION: bootstrap
      ESPBUILD_VERSION: 0.01
      GHR_VERSION: v0.12.1
      GHR_FLAGS: -prerelease -replace

jobs:
  prepare:
    executor: alpine
    steps:
      - run: apk add ca-certificates curl go git build-base
      - run: mkdir -p ~/workspace
      - run: mkdir -p ~/workspace/tools/bin
      - run: curl -LO https://github.com/esplinux/espbuild/releases/download/$ESPBUILD_VERSION/espbuild.tar.gz
      - run: cd ~/workspace/tools; tar xf ~/espbuild.tar.gz
      - run: go mod init .
      - run: go get github.com/tcnksm/ghr@$GHR_VERSION
      - run: cp /root/go/bin/ghr ~/workspace/tools/bin
      - run: export | grep VERSION > ~/workspace/versions.txt
      - run: ~/workspace/tools/bin/ghr -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ~/workspace/versions.txt
      - store_artifacts:
          path: ~/workspace/tools
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - tools

  toybox:
    executor: alpine
    steps:
      - run: apk add ca-certificates 
      - checkout
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Build
          command: |
            export PATH=~/workspace/tools/bin:$PATH
            espbuild toybox.conf
            ghr $GHR_FLAGS -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${VERSION} ~/toybox-*.tar.gz
      - store_artifacts:
          path: ~/workspace/toybox

workflows:
  build:
    jobs:
      - prepare
      - toybox:
          requires:
            - prepare
