version: 2.1

jobs:
  build:
    docker:
      - image: esplinux/bootstrap
    working_directory: /project
    environment:
      VERSION: "0.01"
    steps:
      - checkout
      - run:
          name: Build
          shell: /bin/sh -e
          command: |
            esp add espbuild ghr
            echo gnu >> /etc/esp-repos
            espbuild ${CIRCLE_PROJECT_REPONAME}.conf
            ghr -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} /package

workflows:
  version: 2
  build:
    jobs:
      - build
