version: 2

jobs:
  build:
    docker:
      - image: alpine:3.9
    working_directory: /project
    environment:
      VERSION: bootstrap
      ESPBUILD_VERSION: 0.01
      GHR_VERSION: v0.12.1
    steps:
      - run: apk add ca-certificates curl git go gcc
      - checkout
      - run:
          name: Build
          command: |
            curl -LO https://github.com/esplinux/espbuild/releases/download/$ESPBUILD_VERSION/espbuild-static.tar.gz
            tar xf espbuild-static.tar.gz
            bin/espbuild ${CIRCLE_PROJECT_REPONAME}.conf
            go mod init .
            go get github.com/tcnksm/ghr@$GHR_VERSION
            ~/go/bin/ghr -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} /package
            curl -X POST https://circleci.com/api/v1.1/project/github/esplinux-core/INDEX/tree/bootstrap?circle-token=$CIRCLECI_TOKEN
